# -*- coding: utf-8 -*-
"""Métadonnées de routage : ce que les index.md ne portent pas.

Un enregistrement par destination :
  code, déclencheurs, motif de sous-chemin, conservation courte, registre, arbitrages
Les déclencheurs sont les termes qu'un agent cherche dans le document entrant.
"""

# code : (déclencheurs, sous-chemin, conservation, registre, arbitrages)
R = {
"00": ("non identifié, illisible, doute, plusieurs documents dans un fichier",
       "A classer | A traiter | Scans bruts", "sas, 30j max", "",
       "destination de repli obligatoire quand la confiance est faible"),

"01.1": ("statuts constitutifs, dépôt de capital, annonce légale de constitution, immatriculation, M0, première DBE, non-condamnation, attestation de filiation",
         "à plat", "permanent", "",
         "statuts modifiés depuis la création → 01.2"),
"01.2": ("statuts à jour, statuts modifiés, M2, transfert de siège, changement de dénomination, changement d'objet, transformation, récépissé greffe, annonce légale de modification",
         "AAAA-MM-JJ - Objet de la modification/", "permanent", "",
         "le PV qui décide la modification → 01.3 (copie ici)"),
"01.3": ("PV, procès-verbal, AGO, AGE, assemblée générale, convocation, ordre du jour, rapport de gestion, approbation des comptes, affectation du résultat, feuille de présence, pouvoir, dépôt des comptes au greffe",
         "AAAA/", "permanent", "",
         "comptes annuels eux-mêmes → 04.1"),
"01.4": ("registre des mouvements de titres, ordre de mouvement, compte d'actionnaire, registre des décisions, bénéficiaires effectifs, DBE, registre coté et paraphé",
         "un sous-dossier par registre", "permanent", "",
         "conventions réglementées : pas de registre légal, le rapport → 01.3"),
"01.5": ("nomination du dirigeant, révocation, démission, rémunération du dirigeant, délégation de pouvoir, délégation de signature, convention réglementée, affiliation SSI, TNS, mandat social",
         "NOM Prénom/", "permanent", "",
         "RCMS, assurance du dirigeant → 06.6 ; bulletin du dirigeant assimilé salarié → 03.3"),
"01.6": ("pacte d'associés de NOTRE société, cession de parts, cession d'actions, augmentation de capital, réduction de capital, BSPCE, BSA, action gratuite, compte courant d'associé, table de capitalisation, agrément",
         "un sous-dossier par thème ou par opération", "permanent", "",
         "titres détenus dans une AUTRE société → 08.8 ; levée de fonds → 05.4"),
"01.7": ("marque, INPI, EUIPO, OMPI, dépôt de marque, renouvellement de marque, preuve de propriété d'un nom de domaine, e-Soleau, cession de droits d'auteur, licence de contenu, brevet, dessin et modèle",
         "un sous-dossier par actif", "permanent tant qu'exploité", "",
         "facture de dépôt → 04.3"),
"01.8": ("RGPD, registre des traitements, AIPD, DPA, sous-traitance de données, violation de données, politique de confidentialité, CGV, CGU, mentions légales, médiateur de la consommation, accessibilité numérique, RGAA, charte informatique, charte IA, littératie IA, lanceur d'alerte",
         "RGPD | CGV-CGU | Mediation-consommation | Accessibilite-numerique | Intelligence-artificielle | Politiques et chartes", "10a", "",
         "charte signée par un salarié → 03.2 ; contrat client renvoyant aux CGV → 02.1"),
"01.9": ("mise en demeure, assignation, conclusions, jugement, ordonnance, injonction de payer, huissier, commissaire de justice, avocat, protocole transactionnel, médiation, saisie",
         "AAAA - Partie adverse - Objet/", "10a", "",
         "relance amiable d'une facture que NOUS avons émise → 04.2 ; mise en demeure reçue d'un fournisseur → ici ; sinistre assuré → 06.7"),

"02.1": ("contrat client, contrat de prestation signé, devis accepté, proposition commerciale signée, bon de commande, ordre de service, PV de recette fonctionnelle, CGV acceptées, DPA client, résiliation client",
         "Client/", "10a", "contrats",
         "facture émise → 04.2 ; litige → 01.9 ; livrables → hors périmètre"),
"02.2": ("contrat fournisseur, contrat de prestation reçu, maintenance, conditions générales du fournisseur, attestation de vigilance d'un fournisseur, pièces de vigilance d'un tiers, devis fournisseur accepté",
         "Fournisseur/", "10a", "contrats",
         "facture reçue → 04.3 ; abonnement récurrent → 02.5 ; lettre de mission comptable → 04.7"),
"02.3": ("sous-traitance, contrat de sous-traitance, attestation de vigilance d'un sous-traitant, apport d'affaires, partenariat, distribution, revente, marque blanche, groupement, consortium, commissionnement",
         "Partenaire ou sous-traitant/", "10a", "contrats",
         "prestataire sans lien avec un client → 02.2"),
"02.4": ("bail commercial, bail professionnel, bail précaire, état des lieux, dépôt de garantie, quittance de loyer comme pièce du bail, appel de charges, révision de loyer, indice ILC, domiciliation, coworking, congé, sous-location",
         "Local/", "10a", "contrats",
         "assurance du local → 06.2 ; énergie et ménage → 02.5 ; immeuble détenu comme placement → 08.6"),
"02.5": ("abonnement, SaaS, licence logicielle en cours, hébergement, facture de renouvellement de nom de domaine, télécom, mobile, énergie, électricité, eau, ménage, leasing de matériel, reconduction tacite, résiliation d'abonnement",
         "Service/", "5a", "contrats",
         "facture de l'abonnement → 04.3 ; matériel acheté → 07.6"),
"02.6": ("NDA, accord de confidentialité, engagement de confidentialité isolé",
         "à plat, ou Contrepartie/", "10a", "contrats",
         "NDA inclus dans un contrat plus large → avec ce contrat"),
"02.7": ("modèle de contrat, contrat type, trame, modèle de devis, modèle de mise en demeure",
         "un sous-dossier par type de modèle", "tant qu'un contrat signé en dépend", "",
         "modèles RH → 03.1"),

"03.1": ("registre unique du personnel, DUERP, document unique, affichage obligatoire, convention collective, IDCC, règlement intérieur, accord d'entreprise, TéléAccords, PAPRIPACT, registre de sécurité du personnel, vérification électrique, dangers graves et imminents, registre des alertes, repos hebdomadaire, travail en équipes, DOETH, index égalité",
         "un sous-dossier par registre ou famille", "DUERP 40a, reste 5a", "",
         "registre des questions du CSE → 03.10 ; dossier individuel → 03.2"),
"03.2": ("contrat de travail, CDI, CDD, avenant, DPAE, promesse d'embauche, fiche de poste, entretien annuel, entretien professionnel, avertissement, mise à pied, rupture conventionnelle, licenciement, démission, solde de tout compte, certificat de travail, attestation France Travail, titre de séjour",
         "NOM Prénom/01 Embauche | 02 Vie du contrat | 03 Sortie", "5a après départ", "",
         "bulletin de paie → 03.3 ; arrêt de travail et congés → 03.7 ; avis médical → 03.8"),
"03.3": ("bulletin de paie, bulletin de salaire, journal de paie, livre de paie, DSN, net-entreprises, bordereau de cotisations, état des charges sociales, variables de paie",
         "AAAA/AAAA-MM/", "5a employeur, 50a bulletin électronique", "",
         "notes de frais → 04.4 ; contrat mutuelle → 06.4"),
"03.4": ("URSSAF, AGIRC-ARRCO, retraite complémentaire, prévoyance, mutuelle obligatoire, médecine du travail, SPST, OPCO, SSI, DSI, contrôle URSSAF, lettre d'observations, DUE, notice d'information, notre propre attestation de vigilance",
         "Organisme/", "6a à 10a", "",
         "bordereau mensuel → 03.3 ; contrat d'assurance mutuelle → 06.4"),
"03.5": ("annonce d'emploi, offre d'emploi, CV, candidature, lettre de motivation, entretien de recrutement, grille d'entretien, test de recrutement, refus de candidature, cabinet de recrutement",
         "AAAA-MM - Intitulé du poste/ | CV-theque/", "5a après pourvoi du poste", "",
         "candidat retenu → 03.2 ; CV spontané → sous-dossier CV-theque, 2a"),
"03.6": ("plan de développement des compétences, convention de formation, convocation à une formation, émargement, attestation de formation, certificat de formation, prise en charge OPCO, SST, habilitation électrique",
         "AAAA/AAAA-MM - Intitulé - Organisme/", "10a", "",
         "facture de formation → 04.3 ; Qualiopi de l'entreprise → 07.5"),
"03.7": ("demande de congés, planning des congés, compteur de congés, arrêt de travail, arrêt maladie, IJSS, subrogation, maternité, paternité, congé parental, relevé d'heures, heures supplémentaires, astreinte, forfait jours, avenant de télétravail",
         "AAAA/Conges | Arrets de travail | Temps de travail", "5a", "",
         "certificat médical détaillé : ne pas conserver ; avis d'aptitude → 03.8"),
"03.8": ("visite médicale, visite d'information et de prévention, avis d'aptitude, inaptitude, aménagement de poste, accident du travail, DAT, maladie professionnelle, taux AT/MP, registre des accidents bénins, plan de prévention, fiche de données de sécurité, harcèlement",
         "Suivi medical/NOM Prénom | Accidents du travail/AAAA | Prevention", "10a, 40a exposition", "",
         "DUERP → 03.1 ; arrêt de travail → 03.7"),
"03.9": ("convention de stage, stagiaire, gratification, contrat d'apprentissage, apprenti, professionnalisation, CFA, aide à l'embauche ASP, contrat de mission, freelance, indépendant, portage salarial, cession de droits du freelance",
         "Stagiaires | Alternants | Freelances /NOM Prénom/", "5a à 10a", "",
         "facture du freelance → 04.3 ; prestataire en société → 02.2"),
"03.10": ("CSE, comité social et économique, élection professionnelle, protocole préélectoral, PV d'élection, PV de carence, liste électorale, réunion du CSE, consultation du CSE, BDESE, heures de délégation, registre des questions du CSE, salarié protégé",
         "Mandature AAAA-AAAA/", "permanent pour les PV d'élection", "",
         "accords d'entreprise → 03.1"),

"04.1": ("bilan, compte de résultat, annexe, plaquette, liasse fiscale, 2065, 2050, 2033, grand livre, balance générale, journal comptable, FEC, inventaire, rapport du commissaire aux comptes, situation intermédiaire",
         "AAAA/ (ou AAAA-MM_AAAA-MM si exercice décalé)", "permanent pour les états, 10a pour les livres", "",
         "déclarations fiscales → 04.6 ; PV d'approbation → 01.3"),
"04.2": ("facture émise, facture de vente, facture client, avoir client, facture d'acompte, journal des ventes, relance de facture, échéancier accordé",
         "AAAA/AAAA-MM/", "10a", "",
         "contrat ou devis signé → 02.1 ; impayé en contentieux → 01.9"),
"04.3": ("facture fournisseur, facture d'achat, facture reçue, avoir fournisseur, note d'honoraires, honoraires, quittance de loyer comme pièce comptable, ticket de caisse, reçu, journal des achats",
         "AAAA/AAAA-MM/", "10a", "",
         "dépense avancée par une personne → 04.4 ; bien amorti au-delà de 500 € HT → copie en 04.5 ; contrat → 02.2 ou 02.5"),
"04.4": ("note de frais, frais de déplacement, indemnité kilométrique, barème kilométrique, repas d'affaires, hôtel, péage, train, carburant remboursé, politique de frais",
         "AAAA/AAAA-MM/", "10a", "",
         "facture au nom de l'entreprise → 04.3"),
"04.5": ("immobilisation, tableau d'amortissement d'un bien, amortissement, crédit-bail, LOA, option d'achat, mise au rebut, cession d'immobilisation, registre des immobilisations",
         "AAAA - Désignation - Fournisseur/", "détention + 10a", "immobilisations",
         "inventaire physique et attribution → 07.6 ; titres et participations → 08"),
"04.6": ("CA3, CA12, déclaration de TVA, crédit de TVA, DEB, EMEBI, 2571, 2572, acompte d'IS, solde d'IS, CFE, CVAE, 1447, taxe sur les salaires, TVS, C3S, avis d'imposition, proposition de rectification, contrôle fiscal, rescrit, attestation de régularité fiscale, 3916",
         "Impôt/AAAA/", "10a", "",
         "liasse fiscale → 04.1 ; dossier CIR complet → 05.3 ; calcul de plus-value sur placement → 08.9"),
"04.7": ("lettre de mission, expert-comptable, commissaire aux comptes, CAC, rapport général, rapport spécial, mandat EDI, EDI-TDFC, questionnaire de clôture, lettre d'affirmation",
         "Expert-comptable | Commissaire aux comptes /Cabinet/", "10a", "",
         "honoraires facturés → 04.3"),
"04.8": ("budget, prévisionnel, plan de trésorerie, tableau de bord, business plan, seuil de rentabilité, balance âgée, reporting interne",
         "AAAA/Budget | Tresorerie | Tableaux de bord", "5a", "",
         "prévisionnel transmis à un financeur → copie dans 05.2, 05.3 ou 05.4"),
"04.9": ("plateforme agréée, PA, PDP, plateforme de dématérialisation, Factur-X, e-reporting, piste d'audit fiable, PAF, statut de cycle de vie, annuaire de facturation, portabilité de plateforme, rejet de facture",
         "Plateforme agreee | Piste d'audit fiable | Exports/AAAA | Incidents", "10a", "",
         "le CONTRAT avec la plateforme agréée → 02.5 (registre contrats), avec une copie ici ; seuls les flux, les incidents et la PAF restent ici ; les factures elles-mêmes → 04.2 et 04.3 ; logiciel de facturation → 02.5"),

"05.1": ("relevé de compte, relevé bancaire, convention de compte, RIB, IBAN, procuration bancaire, habilitation, KYC bancaire, agios, échelle d'intérêts, clôture de compte, attestation de solde",
         "Banque - Type de compte/Releves/AAAA/", "10a", "",
         "compte à terme et livret → 08.2 ; relevé de prestataire de paiement → 05.5"),
"05.2": ("contrat de prêt, offre de prêt, tableau d'amortissement d'emprunt, PGE, prêt d'honneur, crédit-bail financier, affacturage, Dailly, découvert autorisé, assurance emprunteur, remboursement anticipé, mainlevée",
         "AAAA - Établissement - Objet - Montant/", "10a", "contrats",
         "caution ou nantissement adossé → 05.6 ; relevé du compte débité → 05.1"),
"05.3": ("subvention, convention de subvention, Bpifrance, ADEME, fonds européens, conseil régional, CIR, CII, JEI, 2069-A, aide à l'embauche, ASP, demande de versement, rapport d'avancement",
         "AAAA - Organisme - Dispositif/", "10a après dernier versement", "",
         "prêt à rembourser → 05.2 ; levée de fonds privée → 05.4"),
"05.4": ("term sheet, lettre d'intention, contrat d'investissement, BSA-AIR, obligation convertible, bulletin de souscription de NOS titres, attestation de dépôt des fonds, due diligence de NOTRE levée, data room de NOTRE levée, reporting investisseurs, closing",
         "AAAA - Nom de l'opération/", "permanent", "",
         "pacte d'associés de NOTRE société → 01.6 ; subvention publique → 05.3"),
"05.5": ("carte bancaire professionnelle, TPE, terminal de paiement, monétique, prestataire de paiement, payout, mandat SEPA, ICS, RUM, prélèvement, chéquier, remise de chèques, chargeback, contestation de paiement",
         "Moyen ou prestataire/", "10a", "",
         "relevé de compte bancaire → 05.1"),
"05.6": ("caution personnelle, cautionnement, garantie bancaire, garantie à première demande, nantissement, gage, hypothèque, garantie Bpifrance, dépôt de garantie reçu, retenue de garantie, mainlevée, lettre d'intention de garantie",
         "Donnees | Recues /Contrepartie ou contrat garanti/", "10a après mainlevée", "",
         "contrat de prêt garanti → 05.2 ; bail garanti → 02.4"),

"06.1": ("RC professionnelle, RC Pro, responsabilité civile professionnelle, RC exploitation, attestation RC Pro, questionnaire de souscription",
         "Assureur - N° contrat/", "10a après fin", "assurances",
         "sinistre → 06.7"),
"06.2": ("multirisque, multirisque professionnelle, incendie, dégât des eaux, vol, bris de machine, RC occupant, attestation pour le bailleur",
         "Assureur - N° contrat/", "10a après fin", "assurances",
         "bail et états des lieux → 02.4"),
"06.3": ("carte verte, assurance automobile, mémo véhicule assuré, relevé d'information, bonus-malus, assurance mission, conducteur désigné au contrat",
         "Assureur - N° contrat/", "5a après fin", "assurances",
         "carte grise et entretien → 07.4 ; constat et sinistre → 06.7"),
"06.4": ("mutuelle, complémentaire santé, prévoyance collective, contrat responsable, Madelin, GSC, PER entreprise, tableau de garanties, prévoyance TNS",
         "Assureur - N° contrat/", "permanent", "assurances",
         "DUE, notices et affiliations des salariés → 03.4 et 03.2"),
"06.5": ("assurance cyber, cyber-risques, rançongiciel couvert, questionnaire de sécurité, frais de notification RGPD",
         "Assureur - N° contrat/", "10a après fin", "assurances",
         "politique de sécurité → 01.8 ; incident survenu → 06.7"),
"06.6": ("RCMS, RC des mandataires sociaux, D&O, homme-clé, protection juridique professionnelle",
         "Assureur - N° contrat/", "10a après fin", "assurances",
         "mandats et nominations → 01.5"),
"06.7": ("déclaration de sinistre, constat amiable, expertise, rapport d'expertise, contre-expertise, indemnisation, décompte d'indemnité, franchise appliquée, plainte, recours contre un tiers",
         "AAAA-MM-JJ - Contrat - Objet/", "10a après règlement", "",
         "litige judiciaire qui en découle → 01.9"),
"06.8": ("décennale, assurance décennale, dommages-ouvrage, PV de réception, réception des travaux, réserves, levée de réserves, parfait achèvement, garantie biennale, DOE, DIUO, PPSPS, attestation décennale du sous-traitant",
         "Assureur - N° contrat/ puis AAAA - Client - Chantier/", "10a après réception", "assurances",
         "sinistre déclaré → 06.7 ; contrat client → 02.1 ; sous-traitance → 02.3"),

"07.1": ("INSEE, avis de situation SIRENE, greffe, guichet unique, formalites.entreprises, RNE, CCI, CMA, douane, EORI, préfecture, mairie, enseigne, CNIL récépissé, syndicat professionnel, identifiants de l'entreprise",
         "Organisme/", "10a", "",
         "impôts → 04.6 ; URSSAF et OPCO → 03.4 ; formalités statutaires → 01.2"),
"07.2": ("courrier, lettre recommandée, LRAR, accusé de réception, preuve de dépôt, LRE, recommandé électronique, réexpédition de courrier",
         "AAAA/Entrant | Sortant", "5a, 10a pour les recommandés", "recommandés",
         "si le courrier concerne un dossier existant, il va DANS ce dossier"),
"07.3": ("registre de sécurité du site, vérification périodique, extincteur, alarme, désenfumage, ascenseur, exercice d'évacuation, plan d'évacuation, consignes de sécurité, badge, clé, registre public d'accessibilité, déchets, tri 8 flux, attestation de valorisation, Trackdéchets, OPERAT, décret tertiaire, relevé de compteur, syndic",
         "Site/", "occupation + 10a", "",
         "bail → 02.4 ; contrats énergie et ménage → 02.5 ; assurance → 06.2"),
"07.4": ("carte grise, certificat d'immatriculation, certificat de cession, contrôle technique, entretien du véhicule, carnet d'entretien, amende, avis de contravention, désignation du conducteur, LLD, LOA véhicule, restitution de véhicule, carte carburant, télépéage",
         "Immatriculation - Marque Modèle/", "détention + 10a", "",
         "assurance du véhicule → 06.3 ; indemnités kilométriques → 04.4"),
"07.5": ("Qualiopi, ISO 9001, ISO 27001, certification, audit de certification, non-conformité, plan d'actions, certificat de conformité, référencement fournisseur, questionnaire fournisseur, déclaration d'activité de formation, NDA formation, bilan pédagogique et financier, BPF",
         "Certification ou label/", "permanent", "",
         "formations suivies par les salariés → 03.6"),
"07.6": ("inventaire du matériel, numéro de série, remise de matériel, restitution de matériel, prêt de matériel, garantie constructeur, extension de garantie, inventaire des licences détenues, clé de licence, DEEE, attestation d'effacement, mise au rebut, recyclage",
         "Inventaire | Remises et restitutions | Garanties | Licences | Mises au rebut", "détention + 10a", "matériel",
         "facture d'achat → 04.3 et 04.5 ; abonnement SaaS → 02.5"),
"07.7": ("DC1, DC2, DC4, DUME, ATTRI1, acte d'engagement, mémoire technique, appel d'offres, avis de publicité, règlement de consultation, CCTP, CCAP, certificat de capacité, marché public, attribution, rejet d'offre",
         "Dossier permanent/ puis AAAA-MM - Acheteur - Objet/", "10a après exécution", "",
         "client privé → 02.1 ; attestations en cours de validité → 97 Kit administratif"),

"08.1": ("politique de placement, note de décision d'investissement, intention de détention, mandat de gestion, convention de conseil en investissement, profil de risque, rapport d'adéquation, questionnaire de connaissance, arbitrage de portefeuille",
         "Decisions/AAAA/ | Intermediaires/Nom/", "permanent", "",
         "le contrat du placement → sous-dossier de sa ligne, 08.2 à 08.8"),
"08.2": ("compte à terme, CAT, DAT, dépôt à terme, compte sur livret, bon de caisse, intérêts courus d'une ligne, pénalité de sortie anticipée, dénouement",
         "AAAA - Banque - Support - Montant - Échéance/", "10a après dénouement", "placements",
         "compte courant d'exploitation → 05.1 ; CAT nanti → garantie dans 05.6"),
"08.3": ("compte-titres, avis d'opéré, achat de titres, vente de titres, action, obligation, OPCVM, SICAV, FCP, ETF, ISIN, dividende, coupon, DIC, PRIIPS, dépréciation de titres, bordereau de transfert",
         "Établissement - N° de compte/Avis d'opere/AAAA/", "détention + 10a", "placements",
         "titre de participation non coté → 08.8 ; SCPI → 08.6 ; fonds non coté → 08.7"),
"08.4": ("contrat de capitalisation, bulletin de souscription d'un contrat de capitalisation, unité de compte, fonds en euros, arbitrage, rachat partiel, rachat total, imposition annuelle forfaitaire, taux de référence",
         "Assureur - N° de contrat/", "durée + 10a", "placements",
         "assurances de l'entreprise → 06 ; prévoyance → 06.4"),
"08.5": ("crypto, crypto-actif, bitcoin, ether, stablecoin, jeton, actif numérique, PSCA, MiCA, PSAN, export de transactions, historique de transactions, portefeuille, wallet, adresse publique, staking, airdrop, valeur vénale",
         "Prestataire ou portefeuille/Exports/AAAA/ | Consolidation/AAAA/", "sans purge tant que détenu", "placements",
         "clés privées et phrases de récupération : JAMAIS ici ; matériel de minage → 04.3"),
"08.6": ("SCPI, OPCI, bulletin de souscription de parts de SCPI, part de SCI, immeuble de rapport, prix de retrait, bulletin trimestriel, relevé de distribution, société de gestion, acte notarié d'investissement",
         "SCPI - Nom | SCI - Nom | Immeuble - Adresse/", "permanent pour les actes", "placements",
         "local occupé par l'entreprise → 02.4 ; immeuble d'exploitation → 04.5"),
"08.7": ("FCPR, FPCI, fonds d'investissement, appel de capitaux, valeur liquidative, distribution de fonds, crowdfunding, crowdlending, financement participatif, obligation non cotée, prêt consenti à un tiers",
         "AAAA - Gestionnaire - Nom du fonds/", "détention + 10a", "placements",
         "prise de contrôle ou influence notable → 08.8 ; emprunt reçu → 05.2"),
"08.8": ("titre de participation, pacte d'associés d'une société où NOUS entrons, filiale, holding, prise de participation, due diligence, garantie d'actif et de passif, management fees, convention de trésorerie, refacturation intragroupe, intégration fiscale, régime mère-fille, tableau des filiales",
         "Nom de la société (SIREN)/", "permanent", "placements",
         "votre propre capital → 01.6 ; titres cotés de trésorerie → 08.3"),
"08.9": ("valorisation au 31/12, attestation de valorisation, état récapitulatif des placements, plus-value réalisée, moins-value, provision pour dépréciation, intérêts courus non échus, cours retenu, horodatage du cours",
         "AAAA/", "10a", "",
         "bilan et liasse → 04.1 ; déclarations → 04.6"),

"97": ("Kbis de moins de 3 mois, copie à jour de notre attestation de vigilance, attestation de régularité fiscale, attestation RC Pro, RIB de l'entreprise, avis de situation SIRENE, liste des bénéficiaires effectifs, pièce d'identité du dirigeant, fiche d'identité de l'entreprise",
       "Kit administratif/ à plat", "version en cours seulement", "",
       "l'original et l'historique restent dans leur domaine : 01.1, 03.4, 04.6, 06.1, 05.1"),
"98": ("dossier clos, salarié parti, contrat terminé, exercice ancien, litige réglé, véhicule revendu, contrat résilié",
       "AAAA de clôture/ + chemin d'origine reproduit", "durée du domaine d'origine", "archives",
       "ce qui ne se détruit jamais reste dans son dossier d'origine"),
"99": ("proposition de suppression, durée écoulée, doublon, purge RGPD, demande d'effacement, scan illisible",
       "AAAA-MM-JJ - Objet du lot/", "délai de grâce 30j", "archives",
       "jamais un document encore dans sa durée, ni un document sous litige ou contrôle"),
}
